[2019-03-13T18:49:07.508] [ERROR] user - 账号或者姓名重复 Error: 账号或者姓名重复
    at createUser (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:70:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-14T20:23:16.201] [ERROR] user - 账号或者姓名重复 Error: 账号或者姓名重复
    at createUser (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:72:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-15T16:21:27.265] [ERROR] cast - 已过24小时，您无操作权限！ Error: 已过24小时，您无操作权限！
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/cast.js:173:17)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:22:5)
[2019-03-15T18:22:29.054] [ERROR] statistics - 查询直通率统计失败 TypeError: Assignment to constant variable.
    at queryDataOfRatio (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/statistics.js:159:14)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:22:5)
[2019-03-15T18:22:29.599] [ERROR] statistics - 查询直通率统计失败 TypeError: Assignment to constant variable.
    at queryDataOfRatio (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/statistics.js:161:14)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:22:5)
[2019-03-18T17:01:03.306] [ERROR] user - 密码错误 Error: 密码错误
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T17:01:13.182] [ERROR] user - 密码错误 Error: 密码错误
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T17:01:20.259] [ERROR] user - 密码错误 Error: 密码错误
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T17:05:27.478] [ERROR] user - 密码错误 Error: 密码错误
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T17:05:50.961] [ERROR] user - 密码错误 Error: 密码错误
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T20:56:00.247] [ERROR] measure - 导出检测记录失败 { Error: ENOENT: no such file or directory, open 'styles.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Sheet.generate (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:31:15)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:41:9
    at Array.forEach (<anonymous>)
    at generateMultiSheets (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:37:10)
    at Object.exports.execute (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:110:2)
    at exportExcel (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:411:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) errno: -2, code: 'ENOENT', syscall: 'open', path: 'styles.xml' }
[2019-03-18T22:54:12.451] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T22:54:20.580] [ERROR] user - 用户不存在 Error: 用户不存在
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:220:15)
    at <anonymous>
[2019-03-18T22:55:13.771] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T22:55:35.271] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T22:56:42.600] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T23:16:00.702] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T23:19:48.708] [ERROR] user - 密码错误 Error: 密码错误
    at login (E:\学习资料\前端开发 学习资料\amorphous_node\controller\user.js:222:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-18T23:25:22.044] [ERROR] measure - 导出检测记录失败 TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at exportExcel (E:\学习资料\前端开发 学习资料\amorphous_node\controller\measure.js:410:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-19T17:55:30.586] [ERROR] measure - 导出检测记录失败 TypeError: row.toArray is not a function
    at Function.Array.unzip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:38:24)
    at Array.GenericCollection.zip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-collection.js:206:18)
    at Array.GenericOrder.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-order.js:39:27)
    at Array.<anonymous> (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:254:47)
    at Object.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-object.js:451:18)
    at SortedSet.compareKeys [as contentCompare] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-map.js:27:20)
    at SortedSet.splay (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:376:31)
    at SortedSet.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:60:14)
    at SortedMap.GenericMap.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-map.js:55:27)
    at addStringCell (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:148:30)
    at Sheet.generate (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:83:12)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:41:9
    at Array.forEach (<anonymous>)
    at generateMultiSheets (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:37:10)
    at Object.exports.execute (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:110:2)
    at exportExcel (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:445:32)
[2019-03-19T17:56:07.595] [ERROR] measure - 导出检测记录失败 TypeError: row.toArray is not a function
    at Function.Array.unzip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:38:24)
    at Array.GenericCollection.zip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-collection.js:206:18)
    at Array.GenericOrder.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-order.js:39:27)
    at Array.<anonymous> (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:254:47)
    at Object.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-object.js:451:18)
    at SortedSet.compareKeys [as contentCompare] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-map.js:27:20)
    at SortedSet.splay (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:376:31)
    at SortedSet.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:60:14)
    at SortedMap.GenericMap.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-map.js:55:27)
    at addStringCell (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:148:30)
    at Sheet.generate (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:83:12)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:41:9
    at Array.forEach (<anonymous>)
    at generateMultiSheets (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:37:10)
    at Object.exports.execute (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:110:2)
    at exportExcel (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:445:32)
[2019-03-19T17:57:23.612] [ERROR] measure - 导出检测记录失败 TypeError: row.toArray is not a function
    at Function.Array.unzip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:38:24)
    at Array.GenericCollection.zip (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-collection.js:206:18)
    at Array.GenericOrder.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-order.js:39:27)
    at Array.<anonymous> (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-array.js:254:47)
    at Object.compare (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/shim-object.js:451:18)
    at SortedSet.compareKeys [as contentCompare] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-map.js:27:20)
    at SortedSet.splay (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:376:31)
    at SortedSet.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/sorted-set.js:60:14)
    at SortedMap.GenericMap.get (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/collections/generic-map.js:55:27)
    at addStringCell (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:148:30)
    at Sheet.generate (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/sheet.js:83:12)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:41:9
    at Array.forEach (<anonymous>)
    at generateMultiSheets (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:37:10)
    at Object.exports.execute (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/excel-export/index.js:110:2)
    at exportExcel (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:445:32)
[2019-03-21T16:10:10.219] [ERROR] user - 用户名不能为空 Error: 用户名不能为空
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:202:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:22:5)
[2019-03-21T22:43:38.597] [ERROR] user - 用户不存在 Error: 用户不存在
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:220:15)
    at <anonymous>
[2019-03-21T22:43:42.662] [ERROR] user - 用户不存在 Error: 用户不存在
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:220:15)
    at <anonymous>
[2019-03-21T22:47:55.697] [ERROR] measure - 新增重卷记录失败 TypeError: Cannot destructure property `orderThickness` of 'undefined' or 'null'.
    at createData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:197:3)
    at <anonymous>
[2019-03-23T21:39:47.989] [ERROR] user - 用户不存在 Error: 用户不存在
    at login (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/user.js:220:15)
    at <anonymous>
[2019-03-24T16:57:01.240] [ERROR] plan - furnaceList is not defined ReferenceError: furnaceList is not defined
    at createData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/plan.js:70:7)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-24T23:57:08.118] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:209:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-25T00:00:54.715] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:210:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-25T00:02:21.612] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:210:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-25T00:06:31.944] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:211:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-25T00:22:30.391] [ERROR] measure - 更新数据失败 ReferenceError: inStoreDate is not defined
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:287:9)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-27T22:22:40.642] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:211:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-27T22:24:14.336] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:211:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-27T22:28:48.638] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:211:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-27T22:30:37.246] [ERROR] measure - 参数错误 Error: 参数错误
    at updateData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/measure.js:211:15)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:317:13)
    at /Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/express/lib/router/index.js:275:10)
    at checkLogin (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/routes/index.js:23:5)
[2019-03-27T22:35:26.726] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:37:48.878] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:38:49.825] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:39:56.182] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:40:27.461] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:45:00.720] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-27T22:46:33.090] [ERROR] measure - 更新数据失败 Error: 更新数据失败
    at MeasureService.allOutStore (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/service/measure.js:85:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-28T23:13:24.454] [ERROR] measure - 添加仓位失败：某些炉号或盘号不存在
[2019-03-28T23:14:20.370] [ERROR] measure - 添加仓位失败：某些炉号或盘号不存在
[2019-03-28T23:14:40.241] [ERROR] measure - 添加仓位失败：某些炉号或盘号不存在
[2019-03-28T23:15:44.814] [ERROR] measure - 添加仓位失败：某些炉号或盘号不存在
[2019-03-28T23:21:31.389] [ERROR] measure - Cast to number failed for value "NaN" at path "coilNumber" for model "Measure"
[2019-03-28T23:24:33.046] [ERROR] measure - Cast to number failed for value "NaN" at path "coilNumber" for model "Measure"
[2019-03-28T23:25:48.805] [ERROR] measure - Cast to number failed for value "NaN" at path "coilNumber" for model "Measure"
[2019-03-29T11:10:28.908] [ERROR] measure - Cannot read property 'data' of undefined
[2019-03-29T11:10:48.034] [ERROR] measure - Cannot read property 'data' of undefined
[2019-03-29T11:25:27.452] [ERROR] measure - item is not defined
[2019-03-29T11:26:35.645] [ERROR] measure - Cannot read property 'furnace' of undefined
[2019-03-29T11:29:36.113] [ERROR] measure - Cannot read property 'furnace' of undefined
[2019-03-29T15:14:13.877] [ERROR] measure - 添加仓位失败：某些炉号或盘号不存在
[2019-03-29T15:24:35.037] [ERROR] measure - furnace is not defined
[2019-03-29T15:24:58.153] [ERROR] measure - 添加仓位失败：炉号06-20190214-02/01，盘号4不存在
[2019-03-29T15:25:53.805] [ERROR] measure - 添加仓位失败：炉号06-20190214-02/01，盘号4不存在
[2019-03-29T15:47:41.156] [ERROR] measure - 添加仓位失败
[2019-03-29T15:48:04.149] [ERROR] measure - 添加仓位失败
[2019-03-29T15:48:42.945] [ERROR] measure - 添加仓位失败
[2019-03-29T15:50:32.958] [ERROR] measure - 添加仓位失败
[2019-03-29T15:50:51.721] [ERROR] measure - 添加仓位失败
[2019-03-29T15:51:09.612] [ERROR] measure - 添加仓位失败
[2019-03-29T15:51:46.446] [ERROR] measure - 添加仓位失败
[2019-03-29T15:52:19.372] [ERROR] measure - 添加仓位失败
[2019-03-29T15:52:52.251] [ERROR] measure - 添加仓位失败
[2019-03-29T15:53:20.507] [ERROR] measure - 添加仓位失败
[2019-03-29T15:54:34.864] [ERROR] measure - 添加仓位失败
[2019-03-29T18:34:16.551] [ERROR] storage - 添加仓位失败
[2019-03-30T16:10:10.111] [ERROR] storage - f is not defined ReferenceError: f is not defined
    at delData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/storage.js:194:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-30T16:11:25.281] [ERROR] storage - f is not defined ReferenceError: f is not defined
    at delData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/storage.js:194:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-30T16:15:43.666] [ERROR] storage - f is not defined ReferenceError: f is not defined
    at delData (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/controller/storage.js:194:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-03-30T16:20:07.055] [ERROR] storage - 添加仓位失败
[2019-03-31T15:03:15.978] [ERROR] storage - 查询库房记录失败 { CastError: Cast to number failed for value "returnRecord" at path "castId" for model "Storage"
    at new CastError (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/error/cast.js:29:11)
    at castNumber (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/cast/number.js:18:11)
    at SchemaNumber.cast (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/schema/number.js:214:10)
    at SchemaNumber.SchemaType.applySetters (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/schematype.js:763:12)
    at SchemaNumber.SchemaType._castForQuery (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/schematype.js:1166:15)
    at SchemaNumber.castForQuery (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/schema/number.js:265:14)
    at SchemaNumber.SchemaType.castForQueryWrapper (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/schematype.js:1135:15)
    at cast (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/cast.js:306:32)
    at model.Query.Query.cast (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/query.js:4024:12)
    at model.Query.Query._countDocuments (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/mongoose/lib/query.js:2062:10)
    at process.nextTick (/Users/yp-tc-m2504/Documents/f2e/amorphous_node/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Cast to number failed for value "returnRecord" at path "castId" for model "Storage"',
  name: 'CastError',
  stringValue: '"returnRecord"',
  kind: 'number',
  value: 'returnRecord',
  path: 'castId',
  reason: undefined,
  model: 
   { [Function: model]
     hooks: Kareem { _pres: [Object], _posts: [Object] },
     base: 
      Mongoose {
        connections: [Array],
        models: [Object],
        modelSchemas: [Object],
        options: [Object],
        _pluralize: [Function: pluralize],
        plugins: [Array] },
     modelName: 'Storage',
     model: [Function: model],
     db: 
      NativeConnection {
        base: [Object],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        '$internalEmitter': [Object],
        _listening: false,
        _connectionOptions: [Object],
        name: 'amorphous',
        host: 'localhost',
        port: 27017,
        user: null,
        pass: null,
        client: [Object],
        '$initialConnection': [Object],
        _events: [Object],
        _eventsCount: 2,
        db: [Object] },
     discriminators: undefined,
     '$appliedMethods': true,
     '$appliedHooks': true,
     schema: 
      Schema {
        obj: [Object],
        paths: [Object],
        aliases: {},
        subpaths: {},
        virtuals: [Object],
        singleNestedPaths: {},
        nested: {},
        inherits: {},
        callQueue: [],
        _indexes: [Array],
        methods: [Object],
        methodOptions: {},
        statics: {},
        tree: [Object],
        query: {},
        childSchemas: [],
        plugins: [Array],
        '$id': 7,
        s: [Object],
        _userProvidedOptions: [Object],
        options: [Object],
        '$timestamps': [Object],
        '$globalPluginsApplied': true,
        _requiredpaths: [],
        _indexedpaths: [Array] },
     collection: 
      NativeCollection {
        collection: [Object],
        opts: [Object],
        name: 'Storage',
        collectionName: 'Storage',
        conn: [Object],
        queue: [],
        buffer: false,
        emitter: [Object] },
     Query: { [Function] base: [Object] },
     '$__insertMany': [Function],
     '$init': Promise { [Circular] },
     '$caught': true } }
[2019-03-31T16:37:32.937] [ERROR] storage - 添加仓位失败
